# Build a gentoo stage3 / amd64
FROM ghcr.io/xavierforestier/gentoo-ci:main AS gentoo
ENV JOB_COUNT=16
# Switch to ~amd64 and build world
RUN echo 'sys-apps/file -seccomp' > /etc/portage/package.use/sys-apps-file.use
RUN echo -e 'virtual/imagemagick-tools jpeg tiff\nmedia-gfx/imagemagick jpeg tiff' > /etc/portage/package.use/virtual-imagemagick-tools.use 
RUN echo 'dev-python/pillow webp' > /etc/portage/package.use/dev-python-pillow.use 
RUN echo 'x11-libs/cairo X' > /etc/portage/package.use/x11-libs-cairo.use
RUN echo 'net-proxy/haproxy zlib -slz' > /etc/portage/package.use/net-proxy-haproxy.use
RUN echo 'x11-libs/gdk-pixbuf jpeg' > /etc/portage/package.use/x11-libs-gdk-pixbuf.use
RUN echo -e '*/* PYTHON_TARGETS: -* python3_14\n*/* PYTHON_SINGLE_TARGET: -* python3_14\ndev-lang/python bluetooth' > /etc/portage/package.use/dev-lang-python.use
RUN touch /etc/portage/package.use/zzz.use
RUN FEATURES='-usersandbox' emerge --jobs=${JOB_COUNT} --jobs-tmpdir-require-free-gb=0 -q --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --autounmask-use=y --autounmask-keep-masks=n --autounmask-keep-keywords=n \
    acct-group/haproxy acct-group/mosquitto acct-group/openct acct-group/pcscd acct-user/haproxy acct-user/mosquitto acct-user/pcscd \
    app-admin/logrotate app-admin/sudo app-arch/lz4 app-eselect/eselect-mpg123 app-eselect/eselect-repository app-eselect/eselect-rust app-misc/jq app-misc/mosquitto app-portage/gentoolkit \
    dev-cpp/abseil-cpp dev-cpp/xsimd dev-db/mysql-connector-c dev-debug/gdb dev-lang/orc dev-lang/swig \
    dev-libs/cJSON dev-libs/darts dev-libs/double-conversion dev-libs/isa-l dev-libs/jemalloc dev-libs/libatomic_ops dev-libs/libfastjson dev-libs/liblinear dev-libs/libsodium dev-libs/libtomcrypt dev-libs/libtommath dev-libs/libyaml dev-libs/protobuf dev-libs/xerces-c dev-libs/yajl \
    dev-perl/Clone dev-perl/Devel-CheckLib dev-perl/Encode-Locale dev-perl/File-Listing dev-perl/HTML-Parser dev-perl/HTML-Tagset dev-perl/HTTP-Cookies dev-perl/HTTP-Date dev-perl/HTTP-Message dev-perl/HTTP-Negotiate dev-perl/IO-HTML dev-perl/IO-Socket-INET6 dev-perl/libwww-perl \
    dev-perl/LWP-MediaTypes dev-perl/LWP-Protocol-https dev-perl/MIME-Base32 dev-perl/Net-HTTP dev-perl/Regexp-IPv6 dev-perl/Socket6 dev-perl/Try-Tiny dev-perl/URI dev-perl/WWW-RobotRules dev-perl/XML-Parser \
    dev-python/absl-py dev-python/accessible-pygments dev-python/aiodns dev-python/aiofiles dev-python/aiohappyeyeballs dev-python/aiohttp dev-python/aiohttp-cors dev-python/aiohttp-socks dev-python/aioitertools dev-python/aioresponses dev-python/aiosignal dev-python/aiosmtpd \
    dev-python/aiosqlite dev-python/alabaster dev-python/annotated-types dev-python/appdirs dev-python/argcomplete dev-python/arrow dev-python/asgiref dev-python/asn1crypto dev-python/asyncstdlib dev-python/atomicwrites dev-python/atpublic dev-python/attrs dev-python/automat \
    dev-python/bcrypt dev-python/beniget dev-python/bitarray dev-python/black dev-python/bleach dev-python/blinker dev-python/bottleneck dev-python/brotlicffi dev-python/build \
    dev-python/cachetools dev-python/cbor2 dev-python/cffi dev-python/cfgv dev-python/click dev-python/click-log dev-python/colorama dev-python/colour dev-python/commentjson dev-python/configargparse dev-python/configobj dev-python/constantly dev-python/coverage dev-python/crcmod dev-python/croniter dev-python/cryptography dev-python/cssselect \
    dev-python/dbus-fast dev-python/decorator dev-python/deepdiff dev-python/deepmerge dev-python/deprecated dev-python/distlib dev-python/distro dev-python/dnspython dev-python/docopt \
    dev-python/ecdsa dev-python/elementpath dev-python/email-validator dev-python/ensurepip-setuptools dev-python/ensurepip-wheel dev-python/events dev-python/exceptiongroup dev-python/expandvars \
    dev-python/fastjsonschema dev-python/feedparser dev-python/filelock dev-python/flask dev-python/flit-scm dev-python/fqdn dev-python/freezegun dev-python/fritzconnection dev-python/frozenlist dev-python/ftfy dev-python/furl dev-python/furo \
    dev-python/gast dev-python/geographiclib dev-python/gmpy2 dev-python/google-api-core dev-python/googleapis-common-protos dev-python/google-auth dev-python/google-auth-httplib2 dev-python/google-auth-oauthlib dev-python/grpcio dev-python/grpcio-status \
    dev-python/h11 dev-python/h2 dev-python/hatch-fancy-pypi-readme dev-python/hpack dev-python/html5lib dev-python/httmock dev-python/httpcore dev-python/huawei-lte-api dev-python/hyperframe dev-python/hyperlink \
    dev-python/id dev-python/identify dev-python/ifaddr dev-python/ijson dev-python/imageio dev-python/imagesize dev-python/importlib-metadata dev-python/incremental dev-python/inflect dev-python/inflection dev-python/iniconfig dev-python/intelhex dev-python/isal dev-python/iso8601 dev-python/isodate dev-python/isoduration dev-python/isort dev-python/itsdangerous \
    dev-python/jaraco-classes dev-python/jaraco-collections dev-python/jaraco-itertools dev-python/jaraco-logging dev-python/jeepney dev-python/jmespath dev-python/josepy dev-python/jsonpath-ng dev-python/jsonpickle dev-python/jsonpointer dev-python/jsonschema dev-python/jsonschema-specifications \
    dev-python/keyring dev-python/lark dev-python/linkify-it-py dev-python/logfury dev-python/markdown dev-python/markdown-it-py dev-python/marshmallow dev-python/mdurl dev-python/mechanize dev-python/meson-python dev-python/mock dev-python/msgpack dev-python/multidict dev-python/munch dev-python/mysqlclient \
    dev-python/netaddr dev-python/netifaces dev-python/nh3 dev-python/nodeenv dev-python/numexpr dev-python/numpy dev-python/oauthlib dev-python/opentelemetry-api dev-python/opentelemetry-sdk dev-python/opentelemetry-semantic-conventions dev-python/orderedmultidict dev-python/orderly-set dev-python/orjson \
    dev-python/paho-mqtt dev-python/pandas dev-python/paramiko dev-python/parsedatetime dev-python/path dev-python/pathvalidate dev-python/pbr dev-python/pdm-backend dev-python/peewee dev-python/pexpect dev-python/pkgconfig dev-python/ply dev-python/poetry-core dev-python/pooch dev-python/portalocker dev-python/prettytable dev-python/prompt-toolkit dev-python/propcache dev-python/protobuf dev-python/proto-plus dev-python/ptyprocess dev-python/py dev-python/pyaes dev-python/pyasn1 dev-python/pyasn1-modules dev-python/pycairo dev-python/pycares dev-python/pycountry  dev-python/pycparser dev-python/py-cpuinfo dev-python/pycryptodome dev-python/pydantic-settings dev-python/pygobject dev-python/pygraphviz dev-python/pyjwt dev-python/pynacl dev-python/pyopenssl dev-python/pyotp dev-python/pyparsing dev-python/pypng dev-python/pyprof2calltree dev-python/pyproject-api dev-python/pyproject-hooks  dev-python/pyquery dev-python/pyrfc3339 dev-python/pyserial dev-python/pytest dev-python/pytest-aiohttp dev-python/pytest-asyncio dev-python/pytest-cov dev-python/pytest-freezer dev-python/pytest-rerunfailures dev-python/pytest-timeout dev-python/python-dateutil dev-python/python-discovery dev-python/python-dotenv dev-python/python-jose dev-python/python-magic dev-python/python-mpd2 dev-python/python-multipart dev-python/python-slugify dev-python/python-socks dev-python/pythran dev-python/pytokens dev-python/pytz dev-python/pyyaml \
    dev-python/ratelimit dev-python/readme-renderer dev-python/recurring-ical-events dev-python/redis dev-python/referencing dev-python/regex dev-python/requests-file dev-python/requests-oauthlib dev-python/requests-toolbelt dev-python/rfc3161-client dev-python/rfc3339-validator dev-python/rfc3986 dev-python/rfc3986-validator dev-python/rfc3987 dev-python/rfc8785 dev-python/rich dev-python/roman-numerals dev-python/rpds-py dev-python/rsa dev-python/ruamel-yaml dev-python/ruamel-yaml-clibz \
    dev-python/scipy dev-python/secretstorage dev-python/securesystemslib dev-python/segno dev-python/semantic-version dev-python/semver dev-python/service-identity dev-python/setuptools-rust dev-python/sgmllib3k dev-python/shellingham dev-python/simplejson dev-python/six dev-python/slixmpp dev-python/sniffio dev-python/snowballstemmer dev-python/socksio dev-python/sortedcontainers dev-python/soupsieve dev-python/sphinx dev-python/sphinx-basic-ng dev-python/sphinxcontrib-applehelp dev-python/sphinxcontrib-devhelp dev-python/sphinxcontrib-htmlhelp dev-python/sphinxcontrib-jquery dev-python/sphinxcontrib-jsmath dev-python/sphinxcontrib-qthelp dev-python/sphinxcontrib-serializinghtml dev-python/sphinx-rtd-theme dev-python/sqlparse dev-python/starlette dev-python/stevedore dev-python/strict-rfc3339 dev-python/structlog dev-python/svgwrite \
    dev-python/tabulate dev-python/tempora dev-python/tenacity dev-python/testtools dev-python/text-unidecode dev-python/tldextract dev-python/tokenize-rt dev-python/tomli-w dev-python/tox dev-python/tqdm dev-python/truststore dev-python/tuf dev-python/twine dev-python/twisted dev-python/typeguard dev-python/typer dev-python/typing-inspection dev-python/tzdata dev-python/tzlocal \
    dev-python/uc-micro-py dev-python/ujson dev-python/ukkonen dev-python/unasync dev-python/unpaddedbase64 dev-python/untangle dev-python/uri-template dev-python/uritemplate dev-python/url-normalize dev-python/uv dev-python/uv-build dev-python/uvicorn \
    dev-python/validators dev-python/versioneer dev-python/virtualenv dev-python/voluptuous dev-python/watchdog dev-python/wcwidth dev-python/webcolors dev-python/webencodings dev-python/websocket-client dev-python/websockets dev-python/werkzeug dev-python/wrapt dev-python/wsproto \
    dev-python/xlsxwriter dev-python/xmlschema dev-python/xmltodict dev-python/x-wr-timezone dev-python/yarl dev-python/zeep dev-python/zeroconf dev-python/zipp dev-python/zlib-ng dev-python/zope-interface \
    dev-util/google-perftools dev-util/maturin dev-util/ruff dev-vcs/pre-commit dev-util/pkgcheck dev-util/shellcheck-bin \
    media-libs/freetype media-gfx/graphviz media-gfx/zbar media-libs/alsa-lib media-libs/alsa-topology-conf media-libs/alsa-ucm-conf media-libs/flac media-libs/freeimage media-libs/gd media-libs/libogg media-libs/libpulse media-libs/libsndfile media-libs/libvorbis media-libs/mutagen media-libs/opus media-libs/qhull media-libs/speexdsp media-libs/webrtc-audio-processing \
    media-plugins/alsa-plugins media-sound/lame media-sound/mpg123-base media-sound/pulseaudio-daemon \
    net-libs/libasyncns net-libs/libpcap net-libs/llhttp net-misc/iperf net-misc/socat net-proxy/haproxy sec-keys/openpgp-keys-nmap sys-libs/libunwind sys-libs/zlib-ng virtual/perl-Compress-Raw-Bzip2 virtual/perl-Compress-Raw-Zlib virtual/perl-IO-Compress virtual/perl-MIME-Base64 virtual/perl-Time-Local \
    x11-libs/libICE x11-libs/libSM x11-libs/libXfixes x11-libs/libXi x11-libs/libXtst x11-libs/pango \
    virtual/imagemagick-tools virtual/lapack virtual/cblas virtual/blas virtual/ttf-fonts virtual/libusb virtual/cron virtual/libudev media-video/ffmpeg
RUN FEATURES='-usersandbox' emerge -tNDuq --jobs=${JOB_COUNT} --jobs-tmpdir-require-free-gb=0 @world
# Cleanup
RUN emerge -C sys-apps/man-pages virtual/man 
RUN emerge -t --depclean && rm -rf /var/cache/distfiles/* /var/log/*.log && wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
FROM scratch
COPY --from=gentoo / /
